#!/bin/sh
#!/bin/sh
set -e
URL="https://github.com/carlwhamilton/${1}/archive/refs/tags/v${2}.tar.gz"
STRIP_PREFIX="${1}-${2}"
INTEGRITY="sha256-$(curl --silent --location ${URL} | openssl dgst -sha256 -binary | openssl base64 -A)"
cat <<EOF
{
    "integrity": "${INTEGRITY}",
    "strip_prefix": "${STRIP_PREFIX}",
    "url": "${URL}"
}
EOF
